changelog:
  categories:
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Bugfixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Other
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
  exclude:
    labels:
      - documentation
      - internal
