# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: sdpctl
before:
  hooks:
  - make clean
  - make deps
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  use: github-native
github_urls:
  download: https://github.com/appgate/sdpctl/releases

builds:

  - <<: &build_defaults
      binary: "{{ if .IsSnapshot }}{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ else }}{{ .ProjectName }}{{ end }}"
      main: ./main.go
      ldflags:
        - -s -w -X "github.com/appgate/sdpctl/cmd.version={{ if .Tag }}{{ .Tag }}{{ else }}dev{{ end }}"
        - -X "github.com/appgate/sdpctl/cmd.commit={{ .FullCommit }}"
        - -X "github.com/appgate/sdpctl/cmd.buildDate={{ .Date }}"
    id: macos
    goos: [darwin]
    goarch: [arm64, amd64]
    env:
      - CGO_ENABLED=1
    hooks:
      post:
        - "{{ .Env.HOOK_PATH }}/sign-macos.sh '{{ .Path }}'"

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - "{{ .Env.HOOK_PATH }}/sign-windows.sh '{{ .Path }}'"


universal_binaries:
  - replace: false
    id: macos
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"


# signs:
#   # TODO add binaries here too, not only checksum
#   # https://goreleaser.com/ci/actions/?h=sign#signing
#   - id: macos_binary_sign
#     artifacts: "{{ if .IsSnapshot }}none{{ else }}binary{{ end }}"
#     ids:
#       - macos
#     cmd: "{{ .Env.HOOK_PATH }}/sign-macos.sh"
#     args:
#       - "{{ .Path }}"
#   - id: windows_binary_sign
#     artifacts: "{{ if .IsSnapshot }}none{{ else }}binary{{ end }}"
#     ids:
#       - windows
#     cmd: "{{ .Env.HOOK_PATH }}/sign-windows.sh"
#     args:
#       - "{{ .Path }}"
#   - id: linux_binary_sign
#     artifacts: "{{ if .IsSnapshot }}none{{ else }}binary{{ end }}"
#     ids:
#       - linux
#     args:
#       - "--batch"
#       - "--local-user"
#       - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
#       - "--output"
#       - "${signature}"
#       - "--detach-sign"
#       - "${artifact}"

nfpms:
  - homepage: https://www.appgate.com
    maintainer: Appgate Cybersecurity Inc <appgatesdp.support@appgate.com>
    description: |-
      Official command line tool for managing
      Appgate SDP Collectives
    license: MIT
    vendor: Appgate Cybersecurity, Inc
    section: utils
    formats:
      - deb
      - rpm
    contents:
      - src: ./build/bash_completion
        dst: /usr/share/bash-completion/completions/sdpctl
        file_info:
          mode: 0644
          group: root
      - src: ./build/man/*.gz
        dst: /usr/share/man/man3/
        type: documentation
      - src: LICENSE
        dst: /usr/share/doc/sdpctl/copyright
        type: documentation
        file_info:
          group: root
          mode: 0644
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
        - groff-message
    rpm:
      compression: gzip
