# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: sdpctl
env:
  - SNAPSHOT_VERSION={{ .Now.Format "2006.01.02" }}
before:
  hooks:
    - make clean
    - make deps
snapshot:
  name_template: "{{ if .IsSnapshot }}{{ .Env.SNAPSHOT_VERSION }}{{ else }}{{ .Tag }}{{ end }}"
changelog:
  skip: true
github_urls:
  download: https://github.com/appgate/sdpctl/releases

builds:
  - <<: &build_defaults
      binary: "{{ .ProjectName }}"
      main: ./main.go
      buildmode: pie
      flags:
        - -trimpath
      ldflags:
        - -s -w -X "github.com/appgate/sdpctl/cmd.version={{ if .IsSnapshot }}{{ .Env.SNAPSHOT_VERSION }}-dev{{ else }}{{ .Version }}{{ end }}"
        - -X "github.com/appgate/sdpctl/cmd.commit={{ .FullCommit }}"
        - -X "github.com/appgate/sdpctl/cmd.buildDate={{ .Date }}"
        - -X "github.com/appgate/sdpctl/pkg/factory.dockerRegistry={{ .Env.DOCKER_REGISTRY_URL }}"
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0

  - <<: *build_defaults
    id: macos
    goos: [darwin]
    goarch: [arm64, amd64]
    env:
      - CGO_ENABLED=1
    hooks:
      post:
        - "{{ .Env.HOOK_PATH }}/sign-macos.sh '{{ .Path }}'"

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - "{{ .Env.HOOK_PATH }}/sign-windows.sh '{{ .Path }}'"

universal_binaries:
  - replace: false
    id: macos
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"

nfpms:
  - homepage: https://www.appgate.com
    maintainer: Appgate Cybersecurity Inc <appgatesdp.support@appgate.com>
    description: |-
      Official command line tool for managing
      Appgate SDP Collectives
    license: MIT
    vendor: Appgate Cybersecurity, Inc
    section: utils
    formats:
      - deb
      - rpm
    contents:
      - src: ./build/bash_completion
        dst: /usr/share/bash-completion/completions/sdpctl
        file_info:
          mode: 0644
          group: root
      - src: ./build/man/*.gz
        dst: /usr/share/man/man3/
        file_info:
          group: root
          mode: 0644
      - src: LICENSE
        dst: /usr/share/doc/sdpctl/copyright
        file_info:
          group: root
          mode: 0644
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
        - groff-message
        - no-manual-page
    rpm:
      compression: gzip
