name: Announce

on:
  release:
    types: [published]

jobs:
  homebrew:
    name: Homebrew Tap Announce
    runs-on: ubuntu-latest
    steps:
      - name: Send announce event
        run: |
          # Trigger event
          curl -L \
            --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/appgate/homebrew-tap/dispatches \
            -d "{\"event_type\": \"sdpctl_release\", \"client_payload\": {\"version\": \"${{ github.event.release.name }}\", \"unit\": false, \"integration\": true}}"
