name: Announce

on:
  release:
    types: [published]

jobs:
  homebrew:
    name: Homebrew Tap Announce
    runs-on: ubuntu-latest
    steps:
      - name: Send announce event
        run: |
          # Set required variables
          repo_owner="appgate"
          repo_name="homebrew-tap"
          event_type="sdpctl_release"
          version="$GITHUB_REF"

          # Trigger event
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"version\": \"$version\", \"unit\": false, \"integration\": true}}"
